name: deploy-docs

on:
  push:
    branches:
      - master

jobs:

  run:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.56.3'
          # extended: true

      - name: Build
        run: |
          cd docs
          sudo npm install -g vuepress
          sudo vuepress build
          ls .vuepress/dist
          sudo mv .vuepress/dist ../

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: chyroc.cn
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
